#
# Site settings
#
remote_theme: KoderzUnreal/pretty-docs
url: https://koderzunreal.github.io
baseurl: http://runtimemesh.koderz.io
title: &site_title Runtime Mesh Docs
description: &site_description Documentation for the Runtime Mesh Component and affiliated plugins for Unreal Engine!
branding:
  icon:
    name: icon_documents_alt
  highlight: Runtime
  bold: Mesh
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true


#
# Owner
#
owner:
  name: Chris Conway
#  twitter: &site_owner_twitter gcalvo
  copyright:
    notice: 
    author: "[Chris Conway (Koderz)](https://github.com/Koderz)"


#
# Social
#
#open_graph:
#  title: *site_title
#  site_name: *site_title
#  description: *site_description
#  locale: en_US
#  image: /assets/images/thumb.png
#twitter_cards:
#  title: *site_title
#  description: *site_description
#  creator: *site_owner_twitter
#  card: summary_large_image
#  image: /assets/images/thumb.png
#share:
#  facebook:
#    class: fb-like
#    action: like
#    layout: button_count
#    show-faces: false
#    share: false
#  twitter:
#    via: *site_owner_twitter
#    text: &site_description
#    title: Tweet
#  github:
#    repo: LeakyAbstractions/pretty-docs
#    position: right
#    color: red


# Google Analytics
#google_analytics: UA-61670496-5


#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
